// Generated by Selenium IDE
package covid19Test;

import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AllLinkTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "C:\\Users\\Admin\\Documents\\MyTestngProject\\src\\main\\resources\\drivers\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void allLink() {
    driver.get("https://www.covid19india.org/");
    driver.manage().window().maximize();

    WebDriverWait wait = new WebDriverWait(driver, 5); // Starts a wait of a maximum 10 seconds.
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName("a")));

    int TotalCountLink = driver.findElements(By.tagName("a")).size();
    System.out.println("Total links available on the page is:"+TotalCountLink);
    Assert.assertTrue(TotalCountLink>=10);
  }
  @Test
  public void GetAllLinks(){
    driver.get("https://www.covid19india.org/");
    driver.manage().window().maximize();

    WebDriverWait wait = new WebDriverWait(driver, 5); // Starts a wait of a maximum 10 seconds.
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName("a")));

    List<WebElement> AllLinks=driver.findElements(By.tagName("a"));
    List<String> allLinksText = new ArrayList<>();
    for(int i=0;i<AllLinks.size();i++)
    {
      System.out.println(AllLinks.get(i).getText());
      allLinksText.add(AllLinks.get(i).getText());
    }
     Assert.assertTrue(allLinksText.contains("ABC"));
  }
}
