// Generated by Selenium IDE
package covid19Test;

import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KarnatakaCountCasesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "C:\\Users\\Admin\\Documents\\MyTestngProject\\src\\main\\resources\\drivers\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void karnatakaActiveCases() {
    driver.get("https://www.covid19india.org/");
    driver.manage().window().maximize();

    WebDriverWait wait = new WebDriverWait(driver, 5); // Starts a wait of a maximum 10 seconds.
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".is-highlighted > .cell:nth-child(3) > .total")));

    WebElement ActiveElement = driver.findElement(By.cssSelector(".is-highlighted > .cell:nth-child(3) > .total"));
    System.out.println(ActiveElement.getText());
    int expectedCount  = 176598;
    String actualText  = ActiveElement.getText().replaceAll(",", "");

    System.out.println(actualText);

    int actualCount = Integer.parseInt(actualText);
    Assert.assertTrue(actualCount >= expectedCount);
  }
  @Test
  public void karnatakConfirmedCases() {
    driver.get("https://www.covid19india.org/");
    driver.manage().window().maximize();

    WebDriverWait wait = new WebDriverWait(driver, 5); // Starts a wait of a maximum 10 seconds.
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".is-highlighted > .cell:nth-child(2) > .total")));

    WebElement ActiveElement = driver.findElement(By.cssSelector(".is-highlighted > .cell:nth-child(2) > .total"));
    System.out.println(ActiveElement.getText());
    int expectedCount  = 176598;
    String actualText  = ActiveElement.getText().replaceAll(",", "");

    System.out.println(actualText);

    int actualCount = Integer.parseInt(actualText);
    Assert.assertTrue(actualCount >= expectedCount);
  }
  @Test
  public void getPageTitle() {
    driver.get("https://www.covid19india.org/state/KA");

    WebDriverWait wait = new WebDriverWait(driver, 5); // Starts a wait of a maximum 10 seconds.
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".population > h1")));

    String pageTitle = driver.getTitle();
    System.out.println(pageTitle);
    Assert.assertEquals("Coronavirus Outbreak in Karnataka - covid19india.org", pageTitle);

    WebElement population = driver.findElement(By.cssSelector(".population > h1"));
    System.out.println(population.getText());

    String populationText = population.getText().replaceAll(",", "");
    long actualCount = Long.parseLong(populationText);

    System.out.println(actualCount);
    Assert.assertTrue(actualCount>= 122153000l);
  }


}
